name = "my-react-app"
type = "webpack"
account_id = "4ea2ca30b4c56e40752ff78d120fae93"
workers_dev = true

[site]
bucket = "./build"
entry-point = "workers-site"

[site.upload]
format = "service-worker"