name = "rijan-portofolio"
type = "webpack"
account_id = "4ea2ca30b4c56e40752ff78d120fae93"
workers_dev = true

[build.upload]
pages_build_output_dir = "./build"
format = "service-worker"

[build]
command = "yarn build"
main = "src/index.js" 

[dependencies]
react-rounded-image = "2.0.11"
